name: Deploy to Google

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./functions

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: install libraries
      run: npm install
      working-directory: ${{env.working-directory}}
    - name: install firebase
      run: npm i firebase-tools -g  
    - name: deploy
      run: firebase deploy --only functions --token ${{ secrets.FIREBASE_FUNCTIONS_TOKEN }}